const { test, expect } = require('@playwright/test');

test.describe('Task Management & Kanban Flow', () => {
  test.beforeEach(async ({ page }) => {
    // Navigate and assume auth state is injected or login is performed
    // For local testing, we assume a bypassed test PIN or direct navigation
    await page.goto('/app');
  });

  test('Should open Create Task modal and submit a new task', async ({ page }) => {
    // Wait for the Kanban board to load
    await expect(page.locator('.board-container, .kanban-board')).toBeVisible({ timeout: 10000 });
    
    // Click 'New Task' or '+' button
    const newTaskBtn = page.locator('button:has-text("New Task"), button[title="Add Task"], .add-task-btn').first();
    await newTaskBtn.click();
    
    // Check if modal appears
    const modal = page.locator('.modal, dialog').filter({ hasText: 'Task' });
    await expect(modal).toBeVisible();
    
    // Fill in task details
    await page.fill('input[name="title"], input[placeholder*="Title"]', 'E2E Automated Task');
    await page.fill('textarea[name="description"]', 'This is a test description generated by Playwright.');
    
    // Submit task
    await page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').click();
    
    // Modal should close
    await expect(modal).not.toBeVisible();
    
    // New task should appear on the board
    await expect(page.locator('text=E2E Automated Task')).toBeVisible();
  });

  test('Should allow drag and drop of task cards across columns', async ({ page }) => {
    // Ensure board is loaded
    await expect(page.locator('.board-container, .kanban-board')).toBeVisible();
    
    // Setup drag and drop
    // We assume there are multiple columns (.column, .board-column) and cards (.task-card, .card)
    const sourceCard = page.locator('.task-card, .card').first();
    const targetColumn = page.locator('.column, .board-column').nth(1);
    
    // Drag and drop action
    if (await sourceCard.isVisible() && await targetColumn.isVisible()) {
      await sourceCard.dragTo(targetColumn);
      
      // Verify visual state update (card is now inside target column)
      // Implementation details vary by exact DOM structure
      const targetColumnCards = targetColumn.locator('.task-card, .card');
      expect(await targetColumnCards.count()).toBeGreaterThan(0);
    }
  });
});
